databases:
  - name: cloudstore-db
    databaseName: cloudstore_db
    user: cloudstore_user
    plan: free

services:
  - type: web
    name: cloudstore
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn cloudstore.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloudstore-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_REGION_NAME
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
